language: python
python:
  - "3.6"
install:
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install -e .
script:
  - pytest --cov=autodiffpy/ --cov-report term-missing
after_success:
  - codecov
