language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
    - pip install black
script:
    - black --check .
    - pytest --cov=autodiffpy/
after_success:
    - codecov
