language: python
python:
    - "3.6"
install:
    - pip install pytest pytest-cov
    - pip install codecov
    - pip install black
    - pip install .
script:
    - black --check .
    - pytest --cov=autodiffpy/
after_success:
    - codecov
